language: go
go: 1.5.1

install:
  - go get -v -t ./...

script:
  - go build ./...
  - go test -v ./...

before_deploy:
  - go get github.com/laher/goxc
  - goxc -t -bc="freebsd,amd64 linux,amd64 windows,386 darwin,amd64"
  - goxc -tasks='xc archive' -bc="freebsd,amd64 linux,amd64 windows,386 darwin,amd64" -wd cwtail -d .

deploy:
  provider: releases
  file:
    - snapshot/cwtail_darwin_amd64.zip
    - snapshot/cwtail_freebsd_amd64.zip
    - snapshot/cwtail_linux_amd64.tar.gz
    - snapshot/cwtail_windows_386.zip
  on:
    tags: true
    repo: nabeken/cwtail
